baseURL = "https://hackintosh-polska.pl/"
languageCode = "pl-pl"
title = "hackintoshpolska"
theme = "docsy"
enableRobotsTXT = true

contentDir = "content/pl"
offlineSearch = true

[[menu.main]]
    name = "facebook"
    url = "https://facebook.com/groups/hackintoshpolska"

[[menu.main]]
    name = "Ekipa"
    url = "/about"